services:
  calculator-api:
    container_name: calculator-api
    image: calculator-api
    ports:
      - "8080:8080"
    restart: always
    networks:
      - calculator-api-network
  
  prometheus:
    container_name: calculator-api-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    networks:
      - calculator-api-network

  grafana:
    container_name: calculator-api-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - calculator-api-network

networks:
  calculator-api-network:
