global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'calculator-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['calculator-api:8080']
