on:
  push:
    tags:        
      - '*' # Push events to every tag not containing /

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Run tests with Maven
      run: mvn test

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

    - name: Create docker image
      run: docker build --tag calculator-api .

    - name: Start with docker compose
      run: PORT=80 docker compose up -d

    - name: Send email on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: ${{secrets.MAIL_CONNECTION}}
        # Required mail subject:
        subject: ⚠️ Erro Pipeline Calculadora Web
        # Required recipients' addresses:
        to: Ben.FreitasG@gmail.com,RodrigoFreitas2121@gmail.com,glaubersfernandes@gmail.com,anderson.nascimento.info@gmail.com
        # Required sender full name (address can be skipped):
        from: Sistema Calculadora WEB # <user@example.com>
        # Optional HTML body read from file:
        html_body: file://email.html